---
title: "projects"
description: |
  My projects 
output: 
  distill::distill_article:
    css: theme.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
library(htmltools)
source("R/functions.R")
```

# Openscapes

[**Openscapes.org**](https://openscapes.org) is an approach for kinder, better science in less time. 

```{r}
create_proj_card(
  img_src = "images/openscapes_hex.jpg",
  url = "https://openscapes.org",
  title = "Openscapes Champions Program",
  text = "An open data science mentorship program for science teams",
  text2 = ""
)

create_proj_card(
  img_src = "images/nasa-openscapes.png",
  url = "nasa-openscapes.org",
  title = "NASA Openscapes Framework",
  text = "Supporting scientists using data from NASA Earthdata served from the Distributed Active Archive Centers (DAACs) as they migrate workflows to the cloud",
  text2 = ""
)
```
<br><br>

# Ocean Health Index

I was a science program lead for the Ocean Health Index from 2013-2019 and helped amplify our transformation to open data science. 

```{r}
create_proj_card(
  img_src = "images/here_say_media.png",
  url = "https://www.nature.com/articles/s41559-017-0160",
  title = "Our path to better science in less time using open data science tools",
  text = "Data visualization and analysis for Here Say Media, 2021",
  text2 = ""
)

create_proj_card(
  img_src = "images/here_say_media.png",
  url = "https://ohi-science.org",
  title = "OHI Science Website",
  text = "Data visualization and analysis for Here Say Media, 2021",
  text2 = ""
)

```
<br><br>

# Open communities
```{r}
create_proj_card(
  img_src = "images/logo.png",
  url = "https://ijeamaka-a.shinyapps.io/rtistry_gallery/",
  title = "Carpentries",
  text = "A celebration and showcase of art in all of its forms created by the #rstats community. An entry for the RStudio 2021 Shiny Competition, 2021",
   text2 = ""
)

create_proj_card(
  img_src = "images/20210322212954.png",
  url = "https://github.com/Ijeamakaanyene/contouR",
  title = "RLadies",
  text = "An R package for creating patterns using geom_contour(), 2021",
  text2 = ""
)
```

